import xlsxwriter
from .Model import Experiment, Result, Square
import logging

def saveExls(experement:Experiment)->None:
    filename = f"{experement.id}_{experement.description}.xls"
    logging.info(f"save - {filename}")
    workbook = xlsxwriter.Workbook(filename)
    worksheet = workbook.add_worksheet()
    worksheet.write(0, 0, "files name")
    worksheet.write(0, 1, "full_a")
    worksheet.write(0, 2, "full_b")
    worksheet.write(0, 3, "full_c")
    worksheet.write(0, 4, "full_d")
    worksheet.write(0, 5, "full_q")
    worksheet.write(0, 6, "full_k")
    worksheet.write(0, 7, "narrow_a")
    worksheet.write(0, 8, "narrow_b")
    worksheet.write(0, 9, "narrow_d")
    worksheet.write(0, 10, "narrow_q")
    worksheet.write(0, 11, "narrow_w")
    worksheet.write(0, 12, "narrow_v")
    worksheet.write(0, 13, "narrow_k")
    worksheet.write(0, 14, "squarFull.s")
    worksheet.write(0, 15, "squarFull.s1")
    worksheet.write(0, 16, "squarFull.s2")
    worksheet.write(0, 17, "squarNarrow.s")
    worksheet.write(0, 18, "squarNarrow.s1")
    worksheet.write(0, 19, "squarNarrow.s2")
    worksheet.write(0, 20, "squarNarrow.s3")
    for i in range(len(experement.meterings)):
        worksheet.write(i+1, 0, experement.meterings[i].description)
        result = experement.meterings[i].result
        worksheet.write(i+1, 1, result.full_a)
        worksheet.write(i+1, 2, result.full_b)
        worksheet.write(i+1, 3, result.full_c)
        worksheet.write(i+1, 4, result.full_d)
        worksheet.write(i+1, 5, result.full_q)
        worksheet.write(i+1, 6, result.full_k)
        worksheet.write(i+1, 7, result.narrow_a)
        worksheet.write(i+1, 8, result.narrow_b)
        worksheet.write(i+1, 9, result.narrow_d)
        worksheet.write(i+1, 10, result.narrow_q)
        worksheet.write(i+1, 11, result.narrow_w)
        worksheet.write(i+1, 12, result.narrow_v)
        worksheet.write(i+1, 13, result.narrow_k)
        logging.info(f" sqF -{result.squarFull}")
        logging.info(f" sqF -{result.squarFull.s[0]}")
        logging.info(f" sqF -{result.squarFull.s1[0]}")
        worksheet.write(i+1, 14, result.squarFull.s[0])
        worksheet.write(i+1, 15, result.squarFull.s1[0])
        worksheet.write(i+1, 16, result.squarFull.s2[0])
        worksheet.write(i+1, 17, result.squarNarrow.s[0] if result.squarNarrow.s!=None else "")
        worksheet.write(i+1, 18, result.squarNarrow.s1[0] if result.squarNarrow.s1!=None else "")
        worksheet.write(i+1, 19, result.squarNarrow.s2[0] if result.squarNarrow.s2!=None else "")
        worksheet.write(i+1, 20, result.squarNarrow.s3[0] if result.squarNarrow.s3!=None else "")

    workbook.close()
